import type { ApiDatabase, ApiCommand } from '@/types';
import { groupByCategory } from './database';

/**
 * Auto-generates Markdown API documentation from a database. This is what keeps
 * docs honest: the reference is produced from what was actually discovered, not
 * hand-maintained prose that drifts out of date.
 */

function renderCommand(cmd: ApiCommand): string {
  const lines: string[] = [];
  const badge = `\`${cmd.method}\` · ${cmd.confidence}`;
  lines.push(`#### ${cmd.id}`);
  lines.push('');
  lines.push(`${badge}${cmd.mutating ? ' · ⚠️ mutating' : ''}`);
  lines.push('');
  if (cmd.description) lines.push(cmd.description, '');
  if (cmd.params.length > 0) {
    lines.push('| Param | Required | Description | Example |');
    lines.push('| --- | --- | --- | --- |');
    for (const p of cmd.params) {
      lines.push(
        `| \`${p.name}\` | ${p.required ? 'yes' : 'no'} | ${p.description ?? ''} | ${p.example ?? ''} |`,
      );
    }
    lines.push('');
  }
  if (cmd.foundIn?.length) lines.push(`_Found in: ${cmd.foundIn.join(', ')}_`, '');
  return lines.join('\n');
}

export function generateApiMarkdown(db: ApiDatabase): string {
  const out: string[] = [];
  out.push('# ZTE Router API Reference (auto-generated)');
  out.push('');
  out.push(`Generated: ${new Date(db.generatedAt).toISOString()}`);
  if (db.firmware) out.push(`Firmware: \`${db.firmware}\``);
  out.push(`Commands: ${db.commands.length}`);
  out.push('');
  out.push('> Generated by the ZTE Router Manager reverse-engineering engine.');
  out.push('> ⚠️ mutating commands change router state — use with care.');
  out.push('');

  for (const [category, commands] of groupByCategory(db)) {
    out.push(`## ${category} (${commands.length})`);
    out.push('');
    for (const cmd of commands) out.push(renderCommand(cmd));
  }
  return out.join('\n');
}
